package com.tmuxmobile.phase0.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Material 3 color scheme generated from seed #005C4B (Google material-color-utilities).

// Light scheme
val LightPrimary = Color(0xFF005344)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF00A588)
val LightOnPrimaryContainer = Color(0xFF001A14)
val LightInversePrimary = Color(0xFF00E0BA)
val LightSecondary = Color(0xFF21504E)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFF6C9A96)
val LightOnSecondaryContainer = Color(0xFF001A18)
val LightTertiary = Color(0xFF005159)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF579CA5)
val LightOnTertiaryContainer = Color(0xFF00191C)
val LightBackground = Color(0xFFEEFDF6)
val LightOnBackground = Color(0xFF121E1A)
val LightSurface = Color(0xFFEEFDF6)
val LightOnSurface = Color(0xFF121E1A)
val LightSurfaceVariant = Color(0xFFD4E7DF)
val LightOnSurfaceVariant = Color(0xFF3A4A45)
val LightSurfaceTint = Color(0xFF006B58)
val LightInverseSurface = Color(0xFF27332F)
val LightInverseOnSurface = Color(0xFFE6F4ED)
val LightError = Color(0xFF98000A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFF574B)
val LightOnErrorContainer = Color(0xFF360001)
val LightOutline = Color(0xFF576862)
val LightOutlineVariant = Color(0xFF84968F)
val LightScrim = Color(0xFF000000)
val LightSurfaceBright = Color(0xFFEEFDF6)
val LightSurfaceDim = Color(0xFFC5D3CD)
val LightSurfaceContainer = Color(0xFFE0EEE8)
val LightSurfaceContainerHigh = Color(0xFFD8E6DF)
val LightSurfaceContainerHighest = Color(0xFFCFDDD7)
val LightSurfaceContainerLow = Color(0xFFE9F7F0)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)

// Dark scheme
val DarkPrimary = Color(0xFF00E0BA)
val DarkOnPrimary = Color(0xFF002A21)
val DarkPrimaryContainer = Color(0xFF007B65)
val DarkOnPrimaryContainer = Color(0xFFFFFFFF)
val DarkInversePrimary = Color(0xFF00604E)
val DarkSecondary = Color(0xFFA0D0CB)
val DarkOnSecondary = Color(0xFF002A28)
val DarkSecondaryContainer = Color(0xFF477471)
val DarkOnSecondaryContainer = Color(0xFFFFFFFF)
val DarkTertiary = Color(0xFF8DD2DB)
val DarkOnTertiary = Color(0xFF00292D)
val DarkTertiaryContainer = Color(0xFF2E767E)
val DarkOnTertiaryContainer = Color(0xFFFFFFFF)
val DarkBackground = Color(0xFF091612)
val DarkOnBackground = Color(0xFFE3F1EA)
val DarkSurface = Color(0xFF091612)
val DarkOnSurface = Color(0xFFE3F1EA)
val DarkSurfaceVariant = Color(0xFF3A4A45)
val DarkOnSurfaceVariant = Color(0xFFB8CBC3)
val DarkSurfaceTint = Color(0xFF00E0BA)
val DarkInverseSurface = Color(0xFFD8E6DF)
val DarkInverseOnSurface = Color(0xFF27332F)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF520003)
val DarkErrorContainer = Color(0xFFCF2C27)
val DarkOnErrorContainer = Color(0xFFFFFFFF)
val DarkOutline = Color(0xFF8D9F98)
val DarkOutlineVariant = Color(0xFF5F706A)
val DarkScrim = Color(0xFF000000)
val DarkSurfaceBright = Color(0xFF35413D)
val DarkSurfaceDim = Color(0xFF091612)
val DarkSurfaceContainer = Color(0xFF1A2622)
val DarkSurfaceContainerHigh = Color(0xFF24312D)
val DarkSurfaceContainerHighest = Color(0xFF2F3C37)
val DarkSurfaceContainerLow = Color(0xFF131F1B)
val DarkSurfaceContainerLowest = Color(0xFF030D0A)

val LightColors = lightColorScheme(
        primary = LightPrimary,
        onPrimary = LightOnPrimary,
        primaryContainer = LightPrimaryContainer,
        onPrimaryContainer = LightOnPrimaryContainer,
        inversePrimary = LightInversePrimary,
        secondary = LightSecondary,
        onSecondary = LightOnSecondary,
        secondaryContainer = LightSecondaryContainer,
        onSecondaryContainer = LightOnSecondaryContainer,
        tertiary = LightTertiary,
        onTertiary = LightOnTertiary,
        tertiaryContainer = LightTertiaryContainer,
        onTertiaryContainer = LightOnTertiaryContainer,
        background = LightBackground,
        onBackground = LightOnBackground,
        surface = LightSurface,
        onSurface = LightOnSurface,
        surfaceVariant = LightSurfaceVariant,
        onSurfaceVariant = LightOnSurfaceVariant,
        surfaceTint = LightSurfaceTint,
        inverseSurface = LightInverseSurface,
        inverseOnSurface = LightInverseOnSurface,
        error = LightError,
        onError = LightOnError,
        errorContainer = LightErrorContainer,
        onErrorContainer = LightOnErrorContainer,
        outline = LightOutline,
        outlineVariant = LightOutlineVariant,
        scrim = LightScrim,
        surfaceBright = LightSurfaceBright,
        surfaceDim = LightSurfaceDim,
        surfaceContainer = LightSurfaceContainer,
        surfaceContainerHigh = LightSurfaceContainerHigh,
        surfaceContainerHighest = LightSurfaceContainerHighest,
        surfaceContainerLow = LightSurfaceContainerLow,
        surfaceContainerLowest = LightSurfaceContainerLowest
)

val DarkColors = darkColorScheme(
        primary = DarkPrimary,
        onPrimary = DarkOnPrimary,
        primaryContainer = DarkPrimaryContainer,
        onPrimaryContainer = DarkOnPrimaryContainer,
        inversePrimary = DarkInversePrimary,
        secondary = DarkSecondary,
        onSecondary = DarkOnSecondary,
        secondaryContainer = DarkSecondaryContainer,
        onSecondaryContainer = DarkOnSecondaryContainer,
        tertiary = DarkTertiary,
        onTertiary = DarkOnTertiary,
        tertiaryContainer = DarkTertiaryContainer,
        onTertiaryContainer = DarkOnTertiaryContainer,
        background = DarkBackground,
        onBackground = DarkOnBackground,
        surface = DarkSurface,
        onSurface = DarkOnSurface,
        surfaceVariant = DarkSurfaceVariant,
        onSurfaceVariant = DarkOnSurfaceVariant,
        surfaceTint = DarkSurfaceTint,
        inverseSurface = DarkInverseSurface,
        inverseOnSurface = DarkInverseOnSurface,
        error = DarkError,
        onError = DarkOnError,
        errorContainer = DarkErrorContainer,
        onErrorContainer = DarkOnErrorContainer,
        outline = DarkOutline,
        outlineVariant = DarkOutlineVariant,
        scrim = DarkScrim,
        surfaceBright = DarkSurfaceBright,
        surfaceDim = DarkSurfaceDim,
        surfaceContainer = DarkSurfaceContainer,
        surfaceContainerHigh = DarkSurfaceContainerHigh,
        surfaceContainerHighest = DarkSurfaceContainerHighest,
        surfaceContainerLow = DarkSurfaceContainerLow,
        surfaceContainerLowest = DarkSurfaceContainerLowest
)
